### ISSUE TITLE
osck keys

### ISSUE THREAD

**Issue by flywire** [Ansuel/Decrypt_RBI_Firmware_Utility#1]
[Super Modder: Hacking Technicolor Modems](https://whirlpool.net.au/wiki/hack_technicolor#super_modder_hack_technicolor_modem)

> Decrypting Firmware- Follow instructions with OSCK from [repository](https://pastelink.net/laft)

Model details at: [Technicolor Firmware Repository](https://whirlpool.net.au/wiki/hack_technicolor#hw_model_1622)

**Comment by Ansuel** [comment]
the best thing to do would be a pr 

also do we know the real model instead of the boardname?

**Comment by flywire** [comment]
boardname_map.put("VANT-F", "TG799vac");
		boardname_map.put("DANT-O", "TG797n v3");
		boardname_map.put("VANT-D", "TG789vac [referred as v1]");
		boardname_map.put("VANT-Y", "TG800vac");
		boardname_map.put("VANT-6", "TG789vac v2");
		boardname_map.put("VBNT-L", "TG789vac v2 HP");
		boardname_map.put("VBNT-J", "DJN2130");
		boardname_map.put("VBNT-V", "DJA0230");
		boardname_map.put("VCNT-A", "DJA0231");

[osckKeys.csv](https://github.com/Ansuel/Decrypt_RBI_Firmware_Utility/files/3076762/osckKeys.csv.txt)

**Comment by Ansuel** [comment]
?

**Comment by flywire** [comment]
> a pr

Needs a bit of work

**Comment by Ansuel** [comment]
are you can see the only file to modify is the one linked in the readme

**Comment by flywire** [comment]
Do you know model for vbnt-f, vbnt-k, vbnt-o, vbnt-s and vdnt-o?

**Comment by Ansuel** [comment]
nope :(

**Comment by flywire** [comment]
https://www.ilpuntotecnico.com/forum/index.php/topic,78382.msg229811.html#msg229811
VBNT-F TG789vac Xtream_MOS

https://setuprouter.com/router/technicolor/tg799vn-v2/status-48663-large.htm
vdnt-o TG799vn-v2

Hmm
		boardname_map.put("VBNT-O", "DGA4131");
		boardname_map.put("VBNT-K", "DGA4130");
		boardname_map.put("VBNT-S", "DGA4132");

https://www.hwupgrade.it/forum/showpost.php?p=45889437&postcount=37706
VBNT-O DGA4131FWB

https://www.ilpuntotecnico.com/forum/index.php?topic=78382.msg243048#msg243048
VBNT-K MediaAccess TG789vac Xtream 35b

https://forum.kitz.co.uk/index.php/topic,20343.msg379839.html?PHPSESSID=6513f627b62f98597ee22afc57893e4e#msg379839
vbnt-s DGA4132 **???**
