### ISSUE TITLE
Re-compression after editing

### ISSUE THREAD

**Issue by Petapton** [Ansuel/Decrypt_RBI_Firmware_Utility#16]
Hi, could it be possible to re-compress a bin file back to rbi after having edited something? Also, are there particular reasons why isn't it possible? :)

**Comment by Ansuel** [comment]
Nope... every rbi is signed and will be rejected by the bootloader

**Comment by Petapton** [comment]
Uh, ok. Is it impossible to replicate this signature or just edit rbi file without decompressing it?

**Comment by antnks** [comment]
If I'm not wrong, after dumping all the needed keys, you should be able to generate signature and encrypt back
This repo has key dump script and also RBI decryption: https://github.com/pedro-n-rocha/secr/

**Comment by tosiara** [comment]
No, nevermind. The signature seems to use RSA/DSA

**Comment by antnks** [comment]
As another user pointed out, it seems like signatures are made with RSA/DSA so it is not possible to sign without having the private key
